name: "Agent Delivery Task"
description: "Work item for the delivery agent"
title: "[Agent] "
labels: ["agent"]
body:
  - type: input
    id: target_solution
    attributes:
      label: Target Solution (dev subfolder)
      description: "Folder name under /dev (one ticket = one /dev/<SolutionName>/ folder)"
      placeholder: "FooSolution"
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria / Requirements
      description: "What must be true when done?"
      placeholder: "- ..."
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: Constraints / Notes
      description: "Anything to avoid or special rules (paths, patterns, style)."
      placeholder: "- Must not edit core framework\n- Only touch dev/FooSolution/**"
    validations:
      required: false

  - type: input
    id: test_override
    attributes:
      label: Test Command Override (optional)
      description: "If blank, agent.yml defaults apply."
      placeholder: "dotnet test dev/FooSolution/FooSolution.sln -c Release"
    validations:
      required: false

  - type: input
    id: cc_plan_override
    attributes:
      label: cc_plan_session_override (optional)
      description: "Advanced: override plan session/session-id. Leave blank for default."
      placeholder: "(leave blank for default)"
    validations:
      required: false

  - type: input
    id: cc_impl_override
    attributes:
      label: cc_impl_session_override (optional)
      description: "Advanced: override implementation session/session-id. Leave blank for default."
      placeholder: "(leave blank for default)"
    validations:
      required: false

  - type: dropdown
    id: core_changes_allowed
    attributes:
      label: Core Changes Allowed
      description: "Default is No. If Yes, agent may modify core framework paths for this issue."
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        The agent will maintain the **Implementation Plan**, **Result Summary**, and **PR** sections in the issue body.
